spring:
  application:
    name: springboot-backend
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/ironick_main?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:ironick_backend_u}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        security:
          web:
            csrf:
              CsrfFilter: DEBUG