spring:
    application:
        name: springboot-backend
    datasource:
        password: password
        url: jdbc:mariadb://localhost:3306/nickblog?useSSL=false
        username: nickbloguser
    jpa:
        hibernate:
            ddl-auto: update

server:
  error:
      include-message: always
      include-binding-errors: always

logging:
    level:
        org:
            springframework:
                security:
                    web:
                        csrf:
                            CsrfFilter: DEBUG